/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type MiscInstagram = {
  _id: string;
  _type: "miscInstagram";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  handle?: string;
};

export type MiscSong = {
  _id: string;
  _type: "miscSong";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  artist?: string;
  url?: string;
};

export type MiscWebsite = {
  _id: string;
  _type: "miscWebsite";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  url?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  profileImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  resume?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  email?: string;
  socialLinks?: {
    linkedin?: string;
    instagram?: string;
    twitter?: string;
  };
  funButton?: {
    text?: string;
    url?: string;
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type WorkProject = {
  _id: string;
  _type: "workProject";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  client?: string;
  isActive?: boolean;
  thumbnail?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  videos?: Array<{
    videoTitle?: string;
    url?: string;
    _type: "video";
    _key: string;
  }>;
  orderRank?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | MiscInstagram
  | MiscSong
  | MiscWebsite
  | SanityImageAssetReference
  | SanityFileAssetReference
  | About
  | SanityImageCrop
  | SanityImageHotspot
  | WorkProject
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: WORK_PROJECTS_QUERY
// Query: *[_type == "workProject" && isActive == true] | order(orderRank) {    _id,    title,    "slug": slug.current,    "headline": client,    thumbnail,    "thumbnailLqip": thumbnail.asset->metadata.lqip  }
export type WORK_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  headline: string | null;
  thumbnail: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  thumbnailLqip: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: WORK_PROJECT_SLUGS_QUERY
// Query: *[_type == "workProject" && defined(slug.current)] {    "slug": slug.current  }
export type WORK_PROJECT_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: WORK_PROJECT_QUERY
// Query: *[_type == "workProject" && slug.current == $slug][0] {    title,    "headline": client,    videos[] {      "type": videoTitle,      url    }  }
export type WORK_PROJECT_QUERY_RESULT = {
  title: string | null;
  headline: string | null;
  videos: Array<{
    type: string | null;
    url: string | null;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: ABOUT_QUERY
// Query: *[_type == "about"][0] {    heading,    profileImage,    "profileImageLqip": profileImage.asset->metadata.lqip,    "profileImageWidth": profileImage.asset->metadata.dimensions.width,    "profileImageHeight": profileImage.asset->metadata.dimensions.height,    "resumeUrl": resume.asset->url,    email,    socialLinks,    funButton  }
export type ABOUT_QUERY_RESULT = {
  heading: string | null;
  profileImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  profileImageLqip: string | null;
  profileImageWidth: number | null;
  profileImageHeight: number | null;
  resumeUrl: string | null;
  email: string | null;
  socialLinks: {
    linkedin?: string;
    instagram?: string;
    twitter?: string;
  } | null;
  funButton: {
    text?: string;
    url?: string;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: HEADER_QUERY
// Query: *[_type == "about"][0] {    "twitter": socialLinks.twitter  }
export type HEADER_QUERY_RESULT = {
  twitter: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: MISC_QUERY
// Query: {    "websites": *[_type == "miscWebsite"] { _id, name, url },    "songs": *[_type == "miscSong"] { _id, title, artist, url },    "instagrams": *[_type == "miscInstagram"] { _id, handle }  }
export type MISC_QUERY_RESULT = {
  websites: Array<{
    _id: string;
    name: string | null;
    url: string | null;
  }>;
  songs: Array<{
    _id: string;
    title: string | null;
    artist: string | null;
    url: string | null;
  }>;
  instagrams: Array<{
    _id: string;
    handle: string | null;
  }>;
};

// Source: src/sanity/lib/queries.ts
// Variable: RESUME_QUERY
// Query: *[_type == "about"][0] {    "resumeUrl": resume.asset->url  }
export type RESUME_QUERY_RESULT = {
  resumeUrl: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "workProject" && isActive == true] | order(orderRank) {\n    _id,\n    title,\n    "slug": slug.current,\n    "headline": client,\n    thumbnail,\n    "thumbnailLqip": thumbnail.asset->metadata.lqip\n  }\n': WORK_PROJECTS_QUERY_RESULT;
    '\n  *[_type == "workProject" && defined(slug.current)] {\n    "slug": slug.current\n  }\n': WORK_PROJECT_SLUGS_QUERY_RESULT;
    '\n  *[_type == "workProject" && slug.current == $slug][0] {\n    title,\n    "headline": client,\n    videos[] {\n      "type": videoTitle,\n      url\n    }\n  }\n': WORK_PROJECT_QUERY_RESULT;
    '\n  *[_type == "about"][0] {\n    heading,\n    profileImage,\n    "profileImageLqip": profileImage.asset->metadata.lqip,\n    "profileImageWidth": profileImage.asset->metadata.dimensions.width,\n    "profileImageHeight": profileImage.asset->metadata.dimensions.height,\n    "resumeUrl": resume.asset->url,\n    email,\n    socialLinks,\n    funButton\n  }\n': ABOUT_QUERY_RESULT;
    '\n  *[_type == "about"][0] {\n    "twitter": socialLinks.twitter\n  }\n': HEADER_QUERY_RESULT;
    '\n  {\n    "websites": *[_type == "miscWebsite"] { _id, name, url },\n    "songs": *[_type == "miscSong"] { _id, title, artist, url },\n    "instagrams": *[_type == "miscInstagram"] { _id, handle }\n  }\n': MISC_QUERY_RESULT;
    '\n  *[_type == "about"][0] {\n    "resumeUrl": resume.asset->url\n  }\n': RESUME_QUERY_RESULT;
  }
}
